[package]
name = "ferrowasp-stm32f4"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[lib]
path = "src/lib.rs"

[features]
default = []
bench_spi_timeout_recovery = []
dshot = ["dep:ferrowasp-waveform"]
stm32f401 = ["stm32f4xx-hal/stm32f401"]
stm32f405 = [
    "stm32f4xx-hal/stm32f405",
    "stm32f4xx-hal/uart4",
    "stm32f4xx-hal/usb_fs",
]

[dependencies]
defmt = "1.0.1"
embedded-hal = { workspace = true }
ferrowasp-io-core = { path = "../ferrowasp-io-core" }
ferrowasp-waveform = { path = "../ferrowasp-waveform", optional = true }
heapless = { workspace = true }
rc-pwm = { path = "../rc-pwm" }

[target.'cfg(target_arch = "arm")'.dependencies]
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
stm32f4xx-hal = { git = "https://github.com/stm32-rs/stm32f4xx-hal.git", rev = "78d79609137d5c380320f7bf1a9120967babc61d", features = ["rtic2", "defmt"] }
usb-device = "0.3.2"
usbd-serial = "0.2.2"
