[package]
name = "ferrowasp-app-stm32f401-bringup"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false
build = "build.rs"

[workspace]
resolver = "2"

[[bin]]
name = "ferrowasp-nucleo-f401re"
path = "src/main.rs"
test = false
bench = false

[features]
default = ["board-nucleo-f401re"]
board-nucleo-f401re = ["ferrowasp-stm32f4/stm32f401"]

[dependencies]
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.5"
defmt = "1.0.1"
defmt-rtt = { version = "1.2.0", features = ["disable-blocking-mode"] }
ferrowasp-stm32f4 = { path = "../../crates/ferrowasp-stm32f4", features = ["stm32f401"] }
panic-probe = { version = "1.0.0", features = ["print-defmt"] }
rtic = { version = "2.2.0", features = ["thumbv7-backend"] }
rtic-monotonics = { version = "2.1.0", features = ["cortex-m-systick"] }
stm32f4xx-hal = { git = "https://github.com/stm32-rs/stm32f4xx-hal.git", rev = "78d79609137d5c380320f7bf1a9120967babc61d", features = ["stm32f401", "defmt", "rtic2"] }

[profile.dev.package."*"]
opt-level = "s"

[profile.release]
codegen-units = 1
debug = true
incremental = false
lto = true
opt-level = "s"
