[target.thumbv7em-none-eabihf]
runner = "probe-rs attach --chip STM32F405RG"

rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "info"
CHIPSERIE = "stm32f405"
