[package]
name = "ferroforge-task-blinky"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
test = false
bench = false

[dependencies]
defmt = "1.0.1"
embedded-hal = "1.0.0"
ferroforge = { path = "../../ferroforge" }
fugit = "0.3.9"

[package.metadata.ferroforge]
check-only-dependencies = ["ferroforge"]

[workspace]
